name: Laravel CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests-applicatifs:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code du dépôt
        uses: actions/checkout@v4

      - name: Initialiser PHP 8.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, xml, ctype, iconv, sqlite3
          tools: composer

      - name: Installer les dépendances du projet (Composer)
        run: composer install --no-ansi --no-interaction --no-scripts --prefer-dist

      - name: Préparer l'environnement de configuration
        run: cp .env.example .env

      - name: Générer la clé applicative unique
        run: php artisan key:generate

      - name: Exécuter la suite de tests unitaires et d'intégration
        run: php artisan test
